<?php
/**
 * @package ${PACKAGE}
 * @copyright 2017
 * @author
 */


namespace Copernicus\Managers;


class UsersManager extends Manager
{

    const TABLE_NAME = "users";
    
    public function __construct()
    {
        $this->table = TABLE_NAME;
    }
    
    private function setColumns(){
        $this->columns = [
            'id' => INTEGER,
            'userID' => INTEGER,
            'content' => STRING,
            'created' => STRING
        ];
    }
    
    public function insert(Array $data)
    {
        $data['CREATED'] = date("Y-m-d H:i:s");
        return parent::insert($data); // TODO: Change the autogenerated stub
    }
}